version: '3.1'

services:
  drupal:
    image: sagshar5/custom-drupal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  postgres:
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pw
    secrets:
      - psql-pw
    volumes:
      - ./sample-data:/var/lib/postgresql/data

secrets:
  psql-pw:
    file: psql_password.txt