version: '3'

services:
  proxy:
    image: nginx:1.13 # This is going to use latest version of nginx, i.e. 1.13.x
    ports:
      - '80:80' # exposing 80 on host and sending traffic to container on 80 as well
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  
  web:
    image: httpd # this will use httpd:latest by default.
    