version: '2'
services:
  drupal:
    image: drupal:8.8.2
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    ports:
      - '8080:80'
    
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: brDSLsd

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
    