# create your drupal and postgres config here, based off the last assignment
version: '3.1'

services:
  drupal:
    image: drupal
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    ports:
      - '8080:80'
  
  postgres:
    image: postgres:12.1
    secrets:
      - psql_pw 
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pw
    volumes:
      - drupal-data:/var/lib/postgresql/

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:

secrets:
  psql_pw:
    external: true